### ISSUE TITLE
ICU_RRT_DIAL_YN = FALSE and ICU_RR_DURATION_INT > 0

### ISSUE THREAD

**Issue by Thomas-De-Corte** [ariercole/UNITE-COVID#2]
I think I found the issue in the original curation code:

ICU_RRT_DURATION_INT
working.df$ICU_RRT_DURATION_INT <- as.character(working.df$ICU_RRT_DURATION_INT)
working.df$ICU_RRT_DURATION_INT <- as.numeric(with(working.df, 
                                                     ifelse(ICU_RRT_DURATION_INT %in% c("ND", ""), NA, 
                                                            ICU_RRT_DURATION_INT)))
working.df$ICU_RRT_DURATION_INT <- as.numeric(with(working.df, 
                                                     ifelse(ICU_RRT_DIAL_YN==FALSE | **is.na(ICU_SEDATION_YN)**, NA, 
                                                            ICU_RRT_DURATION_INT)))

I changed the last line:
working.df$ICU_RRT_DURATION_INT <- as.numeric(with(working.df, 
                                                     ifelse(ICU_RRT_DIAL_YN==FALSE | **is.na(ICU_RRT_DURATION_INT)**, NA, 
                                                            ICU_RRT_DURATION_INT)))

**Comment by ariercole** [comment]
Agreed- have incorporated this into version 2.4
