### ISSUE TITLE
ICU_INTOTROPE_DURATION_INT

### ISSUE THREAD

**Issue by Thomas-De-Corte** [ariercole/UNITE-COVID#4]
I think I found another issue in the code:

#ICU_INOTROPE_DURATION_INT
working.df$ICU_INOTROPE_DURATION_INT <- as.character(working.df$ICU_INOTROPE_DURATION_INT)
working.df$ICU_INOTROPE_DURATION_INT <- as.numeric(with(working.df, 
                                                   ifelse(ICU_INOTROPE_DURATION_INT %in% c("ND", ""), NA, 
                                                          ICU_INOTROPE_DURATION_INT)))
working.df$**ICU_RRT_DURATION_INT** <- as.numeric(with(working.df, 
                                                   ifelse(ICU_INOTROPES_YN==FALSE | is.na(ICU_INOTROPES_YN), NA, 
                                                          ICU_INOTROPE_DURATION_INT)))

last line should be changed to:
working.df$**ICU_INOTROPE_DURATION_INT** <- as.numeric(with(working.df, 
                                                   ifelse(ICU_INOTROPES_YN==FALSE | is.na(ICU_INOTROPES_YN), NA, 
                                                          ICU_INOTROPE_DURATION_INT)))

**Comment by ariercole** [comment]
Thanks- fixed!
